
import React from 'react';

const AIDisclaimer: React.FC = () => {
  return (
    <div className="mt-8 p-4 bg-slate-50 dark:bg-slate-900/50 rounded-2xl border border-slate-100 dark:border-slate-800 text-[10px] text-slate-400 dark:text-slate-500 font-medium leading-relaxed">
      <div className="flex items-start gap-3">
        <svg className="w-4 h-4 text-emerald-600 dark:text-emerald-500 shrink-0 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
        <div>
          <p className="font-bold text-slate-600 dark:text-slate-400 uppercase tracking-widest mb-1">AI Transparency Disclosure</p>
          <p>
            Insights on this page are generated by <strong>Google Gemini AI</strong>. Prompts are transmitted securely to Google for processing. 
            FinBlog does not retain prompt logs for model training. AI outputs can be inaccurate or misleading. 
            By using this tool, you acknowledge that this is not professional financial advice. 
            Review <a href="https://ai.google.dev/terms" target="_blank" rel="noopener noreferrer" className="text-emerald-600 underline">Google's Generative AI Terms</a>.
          </p>
        </div>
      </div>
    </div>
  );
};

export default AIDisclaimer;
